app = "forma-atelier-pb"
primary_region = "mad"

[build]
  image = "ghcr.io/pocketbase/pocketbase:latest"

[env]
  PB_DATA_DIR = "/pb_data"

[mounts]
  source = "pb_data"
  destination = "/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
