/// <reference path="../pb_data/types.d.ts" />

// Seed: Populate products from the Forma Atelier mock catalogue
// Run after the initial schema migration

migrate((db) => {
  const products = [
    {
      name: "Vestido Silk Georgette",
      slug: "vestido-silk-georgette",
      description: "Vestido midi en georgette de seda natural. Caída fluida, cuello en V pronunciado y mangas ligeramente acampanadas. Perfectamente equilibrado entre estructura y movimiento.",
      price: 485,
      collection: "lumiere",
      category: "vestidos",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: true,
      composition: "100% Silk Georgette",
      care: JSON.stringify(["Dry clean only", "Store hanging", "Avoid direct sunlight"]),
    },
    {
      name: "Pantalón Lino Sartorial",
      slug: "pantalon-lino-sartorial",
      description: "Pantalón de lino de alto gramaje con pinzas estructuradas. Corte recto, cinturilla alta con pliegues internos. Bolsillos laterales con vivo.",
      price: 295,
      collection: "terra",
      category: "pantalones",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "100% Linen",
      care: JSON.stringify(["Machine wash cold", "Tumble dry low", "Iron medium heat"]),
    },
    {
      name: "Blazer Algodón Estructurado",
      slug: "blazer-algodon-estructurado",
      description: "Blazer en algodón de doble hilo con estructura interna ligera. Solapas entalladas, dos botones forrados, bolsillos de pecho y parche.",
      price: 385,
      collection: "ombra",
      category: "blazers",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: true,
      composition: "97% Cotton, 3% Elastane",
      care: JSON.stringify(["Dry clean recommended", "Hang to dry", "Iron inside out"]),
    },
    {
      name: "Falda Satín Slip",
      slug: "falda-satin-slip",
      description: "Falda midi en satén de acetato. Silueta en A, cierre lateral con cremallera oculta. Forro interior en seda.",
      price: 225,
      collection: "lumiere",
      category: "faldas",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: false,
      composition: "80% Acetate, 20% Silk lining",
      care: JSON.stringify(["Dry clean only", "Store flat", "Avoid moisture"]),
    },
    {
      name: "Top Punto Acanalado",
      slug: "top-punto-acanalado",
      description: "Top de punto acanalado en mezcla de cachemir. Cuello redondo, corte ajustado, largo en la cadera.",
      price: 185,
      collection: "terra",
      category: "tops",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "70% Cashmere, 30% Merino wool",
      care: JSON.stringify(["Hand wash cold", "Dry flat", "Do not wring"]),
    },
    {
      name: "Abrigo Lana Cashmere",
      slug: "abrigo-lana-cashmere",
      description: "Abrigo de corte largo en lana boouclé con mezcla de cashmere. Cuello solapa, doble botonadura y forro interior en seda.",
      price: 895,
      collection: "ombra",
      category: "abrigos",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: true,
      composition: "80% Wool, 20% Cashmere",
      care: JSON.stringify(["Dry clean only", "Store in garment bag", "Avoid prolonged sunlight"]),
    },
    {
      name: "Camisa Seda Medianoche",
      slug: "camisa-seda-medianoche",
      description: "Camisa oversize en seda lavada. Cuello clásico con forma, puños con doble botón. Tonalidad medianoche profunda.",
      price: 345,
      collection: "ombra",
      category: "camisas",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "100% Washed Silk",
      care: JSON.stringify(["Hand wash cold", "Dry flat in shade", "Iron on silk setting"]),
    },
    {
      name: "Pantalón Lana Plisado",
      slug: "pantalon-lana-plisado",
      description: "Pantalón de lana virgen con pliegues frontales y pernera ancha. Cinturilla alta con trabillas, cierre de gancho.",
      price: 365,
      collection: "ombra",
      category: "pantalones",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: false,
      composition: "100% Virgin Wool",
      care: JSON.stringify(["Dry clean only", "Press with steam", "Store hanging"]),
    },
    {
      name: "Corsé Cinturón Piel",
      slug: "corse-cinturon-piel",
      description: "Cinturón corsé en piel de becerro plena flor. Construcción rígida con ballenas internas, cierre de hebilla dorada.",
      price: 265,
      collection: "terra",
      category: "accesorios",
      sizes: JSON.stringify(["XS","S","M","L"]),
      available: true,
      featured: true,
      composition: "Full-grain calfskin leather",
      care: JSON.stringify(["Wipe with dry cloth", "Condition with leather balm", "Store in dust bag"]),
    },
    {
      name: "Vestido Lino Arena",
      slug: "vestido-lino-arena",
      description: "Vestido maxi en lino stonewashed. Silueta recta con pinzas en el busto, abertura lateral en la falda.",
      price: 315,
      collection: "terra",
      category: "vestidos",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "100% Stonewashed Linen",
      care: JSON.stringify(["Machine wash cold", "Tumble dry low", "Iron damp"]),
    },
    {
      name: "Bolso Tote Rafia",
      slug: "bolso-tote-rafia",
      description: "Bolso tote tejido en rafia natural. Asas de cuero natural, interior en lino sin teñir con bolsillo de parche.",
      price: 195,
      collection: "terra",
      category: "accesorios",
      sizes: JSON.stringify(["One size"]),
      available: false,
      featured: false,
      composition: "Natural raffia, vegetable-tanned leather handles",
      care: JSON.stringify(["Spot clean only", "Avoid rain and moisture", "Store stuffed in dust bag"]),
    },
    {
      name: "Jersey Punto Tierra",
      slug: "jersey-punto-tierra",
      description: "Jersey de punto grueso en lana merino sin tratamiento. Cuello redondo amplio, mangas raglan.",
      price: 245,
      collection: "terra",
      category: "jerseys",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "100% Untreated Merino Wool",
      care: JSON.stringify(["Hand wash cold", "Dry flat", "Reshape while damp"]),
    },
    {
      name: "Pantalón Palazzo Fluido",
      slug: "pantalon-palazzo-fluido",
      description: "Pantalón palazzo en crepé de viscosa. Pernera muy ancha y fluida, cinturilla elástica cubierta.",
      price: 275,
      collection: "lumiere",
      category: "pantalones",
      sizes: JSON.stringify(["XS","S","M","L","XL"]),
      available: true,
      featured: false,
      composition: "100% Viscose Crepe",
      care: JSON.stringify(["Machine wash gentle cold", "Hang dry", "Do not iron"]),
    },
  ];

  for (const p of products) {
    const record = new Record(db.findCollectionByNameOrId("products"), p);
    db.save(record);
  }

}, (db) => {
  // Rollback: delete all seeded products
  db.newQuery("DELETE FROM products").execute();
});
